### ISSUE TITLE
application doesn't start up

### ISSUE THREAD

**Issue by jnovotny** [TwilioDevEd/authy2fa-servlets#7]
Hi,

I can't seem to get the application to start

$ mvn compile jetty:run
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.twilio.authy2fa:authy2fa:jar:1.0
[WARNING] 'dependencies.dependency.systemPath' for com.authy:authy-java:jar should not point at files within the project directory, ${project.basedir}/src/main/resources/lib/authy-java.jar will be unresolvable by dependent projects @ line 40, column 25
[WARNING] 'build.plugins.plugin.version' for org.eclipse.jetty:jetty-maven-plugin is missing. @ line 143, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building authy2fa 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ authy2fa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ authy2fa ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] >>> jetty-maven-plugin:9.4.8.v20171121:run (default-cli) > test-compile @ authy2fa >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ authy2fa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ authy2fa ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ authy2fa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/novotny/IdeaProjects/authy2fa-servlets/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ authy2fa ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< jetty-maven-plugin:9.4.8.v20171121:run (default-cli) < test-compile @ authy2fa <<<
[INFO]
[INFO] --- jetty-maven-plugin:9.4.8.v20171121:run (default-cli) @ authy2fa ---
[INFO] Logging initialized @7524ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.446 s
[INFO] Finished at: 2018-01-31T09:49:49+07:00
[INFO] Final Memory: 16M/225M
[INFO] ------------------------------------------------------------------------

However I go to localhost:8080 and the site is down. If I do a "ps -ef | grep java" I don't see anything running. Any chance I can just get a WAR fie maybe?

Thanks, Jason

**Comment by hortega** [comment]
Hi Jason, 
the issue seems to be with the `jetty-maven-plugin` version. I have locked it to a version that is working, would you mind pulling master and giving it another try?

**Comment by jnovotny** [comment]
Thanks a lot, that fixes it!
